version: "3.8"
services:
  movies:
    image: nileshkumar2343/paymovies:latest
    ports:
      - 85:80
    deploy:
      replicas: 3
  train:
    image: nileshkumar2343/paytrain:latest
    ports:
      - 86:80
    deploy:
      replicas: 3
  dth:
    image: nileshkumar2343/paydth:latest
    ports:
      - 87:80
    deploy:
      replicas: 3
  recharge:
    image: nileshkumar2343/payrecharge:latest
    ports:
      - 88:80
    deploy:
      replicas: 3
